# Generated by Django 4.2 on 2024-04-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pagina_inicio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemPortafolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=50)),
                ("sub_titulo", models.TextField(max_length=50)),
                ("imagen", models.ImageField(upload_to="home/portafolio")),
                ("created", models.DateField(auto_now_add=True)),
                ("visible", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Item Portafolio",
                "verbose_name_plural": "Items Portafolio",
            },
        ),
    ]
