# Generated by Django 4.2 on 2024-04-26 03:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("pagina_inicio", "0002_itemportafolio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemportafolio",
            options={
                "ordering": ["-updated"],
                "verbose_name": "Item del Portafolio",
                "verbose_name_plural": "Items del Portafolio",
            },
        ),
        migrations.AddField(
            model_name="itemportafolio",
            name="description",
            field=models.TextField(
                default=django.utils.timezone.now,
                max_length=500,
                verbose_name="Descripción",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itemportafolio",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="itemportafolio",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="itemportafolio",
            name="sub_titulo",
            field=models.CharField(max_length=50, verbose_name="Sub Titulo"),
        ),
        migrations.AlterField(
            model_name="itemportafolio",
            name="titulo",
            field=models.CharField(max_length=50, verbose_name="Titulo"),
        ),
        migrations.AlterField(
            model_name="itemportafolio",
            name="visible",
            field=models.BooleanField(
                default=False, verbose_name="Mostrar en Pagina Web"
            ),
        ),
    ]
