# Generated by Django 4.2 on 2024-04-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pagina_inicio", "0003_alter_itemportafolio_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemportafolio",
            name="visible",
            field=models.BooleanField(
                default=False, verbose_name="Mostrar en la Pagina Web"
            ),
        ),
    ]
