# Generated by Django 4.2 on 2024-04-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pagina_inicio", "0004_alter_itemportafolio_visible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagencarrusel",
            name="description",
            field=models.TextField(max_length=50, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="imagencarrusel",
            name="imagen",
            field=models.ImageField(upload_to="home/carrusel/%Y/%m"),
        ),
        migrations.AlterField(
            model_name="imagencarrusel",
            name="visible",
            field=models.BooleanField(
                default=False, verbose_name="Mostrar en la Pagina Web"
            ),
        ),
        migrations.AlterField(
            model_name="itemportafolio",
            name="imagen",
            field=models.ImageField(upload_to="home/portafolio/%Y/%m"),
        ),
    ]
