# Generated by Django 4.2 on 2024-04-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pagina_inicio", "0005_alter_imagencarrusel_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagencarrusel",
            name="imagen",
            field=models.ImageField(upload_to="home/carrusel/%Y/%m/%d/%H"),
        ),
        migrations.AlterField(
            model_name="itemportafolio",
            name="imagen",
            field=models.ImageField(upload_to="home/portafolio/%Y/%m/%d/%H"),
        ),
    ]
