# Generated by Django 4.2 on 2024-04-30 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("buzopolis_tienda", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColorProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=250, verbose_name="Nombre Color"),
                ),
            ],
        ),
        migrations.RenameIndex(
            model_name="producto",
            new_name="idx_producto_slug",
            old_name="idx_slug_producto",
        ),
        migrations.RenameIndex(
            model_name="producto",
            new_name="idx_producto_precio",
            old_name="idx_precio_producto",
        ),
        migrations.AlterField(
            model_name="tipoproducto",
            name="nombre",
            field=models.CharField(max_length=250, verbose_name="Nombre Categoría"),
        ),
        migrations.AlterField(
            model_name="producto",
            name="color",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="buzopolis_tienda.colorproducto",
            ),
        ),
    ]
